version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - astera-backened
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  astera-backened: 
    build:
      context: .
    container_name: astera-backened
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DB_NAME: ${DATABASE}
      DB_USER: ${USER}
      DB_PASS: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  pgadmin: 
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dashboard
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: